server:
  port: 9411
spring:
  main:
    allow-bean-definition-overriding: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false

# Eureka
eureka:
  instance:
    # 是否用ip注册
    prefer-ip-address: false
    # 实例id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 服务调用的ip地址
    ip-address: ${spring.cloud.client.ip-address}
  client:
    serviceUrl:
      defaultZone: http://localhost:8571/eureka/
#      defaultZone: http://192.168.2.122:8571/eureka/, http://192.168.2.121:8571/eureka/